// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 The PharosVPN Authors

package config

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/knadh/koanf/parsers/yaml"
	"github.com/knadh/koanf/providers/env"
	"github.com/knadh/koanf/providers/file"
	"github.com/knadh/koanf/providers/structs"
	"github.com/knadh/koanf/v2"
	goyaml "gopkg.in/yaml.v3"
)

// DefaultPath is the config file helm reads when none is given on the CLI.
const DefaultPath = "helm.yaml"

// envPrefix scopes environment-variable overrides. A double underscore marks a
// nesting boundary, so HELM_UI__LISTEN overrides ui.listen while a single
// underscore is preserved (HELM_STATE_DIR overrides state_dir).
const envPrefix = "HELM_"

// Load reads configuration from path, then applies HELM_-prefixed environment
// overrides on top. Universal defaults fill any gaps.
func Load(path string) (Config, error) {
	k := koanf.New(".")

	// Layer 1: universal defaults, so a hand-trimmed file still loads.
	if err := k.Load(structs.Provider(common(), "koanf"), nil); err != nil {
		return Config{}, fmt.Errorf("load defaults: %w", err)
	}

	// Layer 2: the on-disk config file.
	if err := k.Load(file.Provider(path), yaml.Parser()); err != nil {
		return Config{}, fmt.Errorf("read %s: %w", path, err)
	}

	// Layer 3: environment overrides.
	if err := k.Load(env.Provider(envPrefix, ".", envKey), nil); err != nil {
		return Config{}, fmt.Errorf("load environment: %w", err)
	}

	var c Config
	if err := k.Unmarshal("", &c); err != nil {
		return Config{}, fmt.Errorf("decode config: %w", err)
	}
	if err := c.Validate(); err != nil {
		return Config{}, err
	}
	return c, nil
}

// envKey maps an environment variable name to a config key path.
func envKey(s string) string {
	s = strings.ToLower(strings.TrimPrefix(s, envPrefix))
	return strings.ReplaceAll(s, "__", ".")
}

// Validate checks invariants that the type system cannot.
func (c Config) Validate() error {
	switch c.Posture {
	case PosturePersonal, PostureEnterprise:
	default:
		return fmt.Errorf("invalid posture %q", c.Posture)
	}
	if c.StateDir == "" {
		return fmt.Errorf("state_dir must not be empty")
	}
	if c.Beacon.Remote && !c.Beacon.Embedded {
		// Remote relays are dialed by the same machinery as the embedded one;
		// disabling the embedded relay while keeping remote is not a state we
		// support in v1.
		return fmt.Errorf("beacon.remote requires beacon.embedded")
	}
	return nil
}

// Write marshals c to YAML at path. It refuses to overwrite an existing file
// unless force is set.
func Write(path string, c Config, force bool) error {
	if !force {
		if _, err := os.Stat(path); err == nil {
			return fmt.Errorf("%s already exists (use --force to overwrite)", path)
		} else if !os.IsNotExist(err) {
			return err
		}
	}
	if dir := filepath.Dir(path); dir != "" {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return err
		}
	}
	body, err := goyaml.Marshal(c)
	if err != nil {
		return fmt.Errorf("marshal config: %w", err)
	}
	header := "# helm configuration — PharosVPN controller\n" +
		"# Generated by `helm init`. Edit freely; see docs/DESIGN.md §12.\n\n"
	return os.WriteFile(path, append([]byte(header), body...), 0o600)
}
